<?xml version="1.0"?>
<package format="3">
  <name>robotx_beacon_plugin</name>
  <version>0.1.0</version>
  <description>Gazebo Harmonic system plugin for RobotX buoy beacon flashing.</description>

  <maintainer email="noreply@example.com">robotx</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>gz-sim8</depend>
  <depend>gz-msgs10</depend>
  <depend>sdformat14</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
